# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DebugingProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inhibit_all_warnings!
  
  # Pods for DebugingProject
  pod 'Masonry', '~> 1.1.0',:inhibit_warnings => false
  pod 'YYModel', '~> 1.0.4',:inhibit_warnings => false
  pod 'JVFloatLabeledTextField', '~> 1.2.2',:inhibit_warnings => false
  pod 'SDWebImage', '~> 5.7.3'
  
  target 'DebugingProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
 target.build_configurations.each do |config|
  if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
     end
   end
  end
end
