# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DebugingProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DebugingProject
  pod 'Masonry', '~> 1.1.0'
  pod 'YYModel', '~> 1.0.4'
  
  target 'DebugingProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
